### ISSUE TITLE
Load on vec does not allow pointer to non-const data.

### ISSUE THREAD

**Issue by steffenlarsen** [KhronosGroup/SYCL-Docs#540]
The `load` member function on `sycl::vec` takes a `multi_ptr<const DataT, ...>` which seems to written that way to allow pointers with and without `const` data. However, because the function is dependent, the conversion from `multi_ptr<DataT, ...>` to `multi_ptr<const DataT, ...>` cannot be resolved. See https://godbolt.org/z/dTdc6K7a9.

Possible solution: Make two overloads of `load` - one with `multi_ptr<std::remove_const_t<DataT>, ...>` and one with `multi_ptr<std::add_const_t<DataT>, ...>`. See https://godbolt.org/z/xs175dc7v.

Inspired by https://github.com/KhronosGroup/SYCL-CTS/pull/870.

**Comment by victor-eds** [comment]
I'm wondering whether this should indeed be solved in `sycl::multi_ptr` instead. Issue to me is that we diverge from C++ pointers in the sense that we miss implicit cv-qualification of `sycl::multi_ptr`, i.e., we should add:

```c++
template <typename OtherElementType,
          typename = std::enable_if_t<std::is_same_v<OtherElementType, std::add_const_t<ElementType>> ||
                                      std::is_same_v<OtherElementType, std::add_volatile_t<ElementType>>>>
operator multi_ptr<OtherElementType, Space, DecorateAddress>() const;
```

Users would expect to be able to call a function receiving `const T *` with `T *`, not sure why that's not also the case with `sycl::multi_ptr`. WDYT?

**Comment by gmlueck** [comment]
@victor-eds: We already have these implicit conversions in `multi_ptr`, but it doesn't solve the problem.  This is because template selection happens before implicit conversions are considered.  Here is a slightly modified version of @steffenlarsen's godbolt example that demonstrates the problem (https://godbolt.org/z/5Pvo13M31).

**Comment by victor-eds** [comment]
True, then the two overloads look like a better solution :+1:
